name: "build and test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  # Cancel previous actions from the same PR or branch except 'main' branch.
  # See https://docs.github.com/en/actions/using-jobs/using-concurrency and https://docs.github.com/en/actions/learn-github-actions/contexts for more info.
  group: concurrency-group::${{ github.workflow }}::${{ github.event.pull_request.number > 0 && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}${{ github.ref_name == 'main' && format('::{0}', github.run_id) || ''}}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazel-contrib/setup-bazel@0.8.5
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true
        # Keep a disk-cache
        disk-cache: true
        # Share repository cache between workflows.
        repository-cache: true
        # enable some flags for CI
        bazelrc: |
          import %workspace%/.aspect/bazelrc/ci.bazelrc
        # keep a cache for MODULE.bazel repos
        external-cache: true
    - run: bazel build --config=built-toolchain //... && bazel test --config=built-toolchain //...

  e2e-workspace-matrix:
    strategy:
      matrix:
        version:
          - version: 5.x # TODO: deprecate by Jan 2025 https://bazel.build/release
            bazelrc:
          - version: 6.x
            bazelrc: |
              import %workspace%/../../.aspect/bazelrc/bazel6.bazelrc
          - version: 7.x
            bazelrc: |
              import %workspace%/../../.aspect/bazelrc/bazel6.bazelrc
              import %workspace%/../../.aspect/bazelrc/bazel7.bazelrc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazel-contrib/setup-bazel@0.8.5
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true
        # Keep a disk-cache
        disk-cache: true
        # Share repository cache between workflows.
        repository-cache: true
        # enable some flags for CI
        bazelrc: |
          import %workspace%/../../.aspect/bazelrc/ci.bazelrc
          ${{ matrix.version.bazelrc }}
    - run: cd e2e/bazel-workspace && USE_BAZEL_VERSION=${{ matrix.version.version }} bazel build //...
