name: "build and test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  # Cancel previous actions from the same PR or branch except 'main' branch.
  # See https://docs.github.com/en/actions/using-jobs/using-concurrency and https://docs.github.com/en/actions/learn-github-actions/contexts for more info.
  group: concurrency-group::${{ github.workflow }}::${{ github.event.pull_request.number > 0 && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}${{ github.ref_name == 'main' && format('::{0}', github.run_id) || ''}}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - uses: bazel-contrib/setup-bazel@0.18.0
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true
        # Keep a disk-cache
        disk-cache: true
        # Share repository cache between workflows.
        repository-cache: true
        # enable some flags for CI
        bazelrc: |
          try-import %workspace%/.aspect/bazelrc/ci.bazelrc
          try-import %workspace%/.github/workflows/ci.bazelrc
          try-import %workspace%/../../.aspect/bazelrc/ci.bazelrc
          try-import %workspace%/../../.github/workflows/ci.bazelrc
        # keep a cache for MODULE.bazel repos
        external-cache: true
    - id: build
      name: building repository
      run: bazelisk build //...
    - id: unit-tests
      name: running unit tests
      run: bazelisk test //...
    - id: prepare-e2e-runner
      name: preparing for e2e
      # workaround for https://github.com/bazel-contrib/setup-bazel/issues/108
      # together with our customized default_test_runner
      run: cat ~/.bazelrc | grep -v output_base > ~/.bazelrc.clean
    - id: e2e-that-should-pass
      name: running mandatory e2e tests
      run: bazelisk test e2e --notest_keep_going
    - id: e2e-that-are-allowed-to-fail
      name: running e2e tests that are allowed to fail
      run: |
        ret_code=0
        bazel test //e2e --notest_keep_going --test_tag_filters=allowed-to-fail || ret_code=$?
        case $ret_code in
          0) echo "All allowed-to-fail tests passed." ;;
          3) echo "::warning::Some allowed-to-fail e2e tests failed or timed out." ;;
          4) echo "No tests matched the allowed-to-fail filter." ;;
          *) exit $ret_code ;;
        esac
